Repository kyma-project/btp-manager, pull requests merged in 2022-12, with the labels that each got.

#48 Update e2e-test-k3s.yml
  .github/workflows/e2e-test-k3s.yml
Labels: size/M, area/ci, lgtm

#50 Update e2e-test-k3s.yml
  .github/workflows/e2e-test-k3s.yml
Labels: size/XS, area/ci, lgtm

#52 Update e2e-test-k3s.yml
  .github/workflows/e2e-test-k3s.yml
Labels: size/XS, area/ci, lgtm

#51 CI/CD #2
  .github/workflows/e2e-test-k3s.yml
  operator/main.go
  testing/k3s-setup.sh
Labels: size/S, area/ci, lgtm

#53 Platform independent tests
  operator/controllers/suite_test.go
Labels: size/XS, lgtm

#54 CI/CD: Add separate action for unit tests
  .github/workflows/unit-tests.yaml
Labels: size/M, area/ci, lgtm

#41 Introduce configurability via CLI parameters and ConfigMap
  docs/configuration.md
  examples/btp-operator-configmap.yaml
  operator/Makefile
  operator/config/rbac/role.yaml
  operator/controllers/btpoperator_controller.go
  operator/controllers/btpoperator_controller_test.go
  operator/main.go
Labels: size/L, area/documentation, lgtm

#29 Refactor processes and tests
  charts/btp-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_btpoperators.operator.kyma-project.io.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrole_btp-manager-manager-role.yaml
  docs/assets/activity_deprovisioning.drawio
  docs/assets/deprovisioning.svg
  operator/Makefile
  operator/controllers/btpoperator_controller.go
  operator/controllers/btpoperator_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/testdata/test-servicebinding.yaml
  operator/controllers/testdata/test-serviceinstance.yaml
  operator/go.mod
  operator/go.sum
  operator/main.go
Labels: area/documentation, size/XXL, lgtm

#37 Statuses and conditions handling
  docs/operations.md
  operator/controllers/btpoperator_controller.go
  operator/controllers/btpoperator_controller_test.go
  operator/controllers/conditions.go
  operator/controllers/conditions_test.go
  operator/go.mod
  operator/go.sum
Labels: size/L, area/documentation, lgtm

#64 Update the CODEOWNERS file
  .github/OWNERS
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/S, area/ci, lgtm

#61 Unify configuration of hard delete timeout
  docs/configuration.md
  examples/btp-operator-configmap.yaml
  operator/controllers/btpoperator_controller.go
  operator/controllers/suite_test.go
  operator/main.go
Labels: area/documentation, size/M, lgtm

#63 Replace Recovered condition reason with Updated
  docs/operations.md
  operator/controllers/btpoperator_controller.go
  operator/controllers/conditions.go
Labels: area/documentation, size/XS, lgtm

#65 Add TWs as code owners
  CODEOWNERS
Labels: size/XS, lgtm

#66 Allow configuring chartPath
  docs/configuration.md
  operator/controllers/btpoperator_controller.go
  operator/controllers/suite_test.go
  operator/main.go
Labels: size/S, area/documentation, lgtm

#67 Update README files
  README.md
  docs/OWNERS
  docs/README.md
Labels: size/S, area/documentation, lgtm

#68 State transitions tests added for Updated reason
  operator/controllers/btpoperator_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/main.go
Labels: size/M, lgtm

#76 Decrease execution time of controller integration test
  .github/workflows/make-test.yaml
  operator/controllers/btpoperator_controller_test.go
Labels: size/M, lgtm

#77 Github Actions: Exclude Readme.md from pipline execution
  .github/workflows/e2e-test-k3s.yml
  .github/workflows/make-test.yaml
Labels: size/S, lgtm

#78 Update CODEOWNERS file
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#79 Improve the README file
  docs/README.md
Labels: area/documentation, size/XS, lgtm

#80 reverting ignore path
  .github/workflows/e2e-test-k3s.yml
  .github/workflows/make-test.yaml
Labels: size/XS, lgtm

#81 Improve the operator README file
  operator/README.md
Labels: size/S, area/documentation, lgtm
