Repository kyma-project/btp-manager, pull requests merged in 2022-11, with the labels that each got.

#14 Deprovisioning
  docs/assets/deprovisioning.svg
  docs/deprovisioning.md
  operator/controllers/btpoperator_controller.go
  operator/controllers/btpoperator_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/module-chart/README.md
Labels: area/documentation, size/XL, lgtm

#24 Custom provisioning - limit operand reconcile to the oldest BtpOperator CR
  operator/api/v1alpha1/btpoperator_types.go
  operator/config/crd/bases/operator.kyma-project.io_btpoperators.yaml
  operator/controllers/btpoperator_controller.go
Labels: size/L, lgtm

#25 Deprovisioning refactor
  operator/controllers/btpoperator_controller.go
  operator/controllers/btpoperator_controller_test.go
  operator/controllers/suite_test.go
  operator/main.go
Labels: size/L, lgtm

#26 Handle Ready state
  operator/controllers/btpoperator_controller.go
Labels: size/M, lgtm

#36 Correct OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm

#35 Provisioning documentation
  docs/assets/activity_deprovisioning.drawio
  docs/assets/activity_provisioning.drawio
  docs/assets/deprovisioning.svg
  docs/assets/provisioning.svg
  docs/deprovisioning.md
  docs/operations.md
  operator/.gitignore
Labels: area/documentation, size/M, lgtm

#39 Installation and uninstallation guide improvement
  Makefile
  README.md
  deployments/prerequisites.yaml
  examples/btp-manager-secret.yaml
  examples/btp-operator.yaml
  operator/.gitignore
Labels: size/M, lgtm

#42 Fix for passing wrong value into cluster.id + sap-btp-manager change …
  operator/controllers/btpoperator_controller.go
Labels: size/S, lgtm
