Repository kyma-project/btp-manager, pull requests merged in 2023-11, with the labels that each got.

#488 Running btp-manager tests on a set of k3s selected versions
  .github/workflows/create-release.yaml
  .github/workflows/label-validator.yml
  .github/workflows/run-e2e-tests-reusable.yaml
  .github/workflows/run-e2e-tests.yaml
  scripts/testing/get-latest-k3s-releases.sh
  scripts/testing/k3s-setup.sh
Labels: size/M, lgtm, kind/enhancement

#489 Using the most recent minor versions of k3s for tests
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/testing/get-latest-k3s-releases.sh
Labels: size/M, lgtm, kind/enhancement

#496 Select k3s1 releases only for end to end testing
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/testing/get-latest-k3s-releases.sh
Labels: lgtm, kind/enhancement

#501 Clobber switch added for curl invocation
  .github/workflows/promote_to_module-manifests.yaml
Labels: lgtm, kind/enhancement

#502 PR body corrected and curl invocation corrected
  .github/workflows/promote_to_module-manifests.yaml
Labels: size/XS, lgtm, kind/enhancement

#497 Documentation update for new E2E (matrix) approach
  docs/contributor/03-10-release.md
  docs/contributor/04-10-workflows.md
Labels: size/S, area/documentation, lgtm, kind/enhancement

#505 Remove 'v' prefix from module-tag
  .github/workflows/run-e2e-tests.yaml
Labels: size/XS, lgtm, kind/enhancement

#506 Remove 'v' prefix from module-tag in workflows
  .github/workflows/create-release.yaml
  .github/workflows/promote_to_module-manifests.yaml
  scripts/build_and_push_locally.sh
  scripts/testing/run_e2e_module_upgrade_tests.sh
Labels: size/S, lgtm, kind/enhancement

#507 Fix autobump step skip
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement

#508 Restore 'v' in module tag for upgrade test
  scripts/testing/run_e2e_module_upgrade_tests.sh
Labels: size/XS, lgtm, kind/enhancement

#504 Convert toggles into docsify tabs
  docs/contributor/01-10-installation.md
  docs/contributor/02-10-operations.md
  docs/user/02-10-usage.md
  docs/user/README.md
Labels: area/documentation, size/M, lgtm, kind/enhancement

#512 Draft release is a must even for dry-run
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement

#513 Removal of security config file
  .github/workflows/promote_to_module-manifests.yaml
Labels: size/S, lgtm, kind/enhancement

#516 Handle skipping final step in E2E tests
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/testing/run_e2e_module_tests.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes
