Repository kyma-project/btp-manager, pull requests merged in 2023-03, with the labels that each got.

#204 Extract the changelog generating logic to an external script
  .github/workflows/create-release.yaml
  scripts/create_changelog.sh
Labels: size/M, lgtm

#206 Remove -w flag from kyma cli command
  Makefile
Labels: size/XS, lgtm

#203 Add item to gopher project board TODO column on auto-update PR
  .github/workflows/auto-update.yml
Labels: size/M, lgtm

#200 Remove reason of conflicting settings message from Ginkgo library
  controllers/suite_test.go
Labels: size/XS, lgtm

#207 LM change a way of versioning images for template
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#205 Add PR description when creating PR for module version bump
  .github/workflows/auto-update.yml
Labels: size/S, lgtm

#201 Include manifests from modue-resources/delete in the deprovisioning
  controllers/btpoperator_controller.go
  docs/operations.md
Labels: size/S, area/documentation, lgtm

#210 Improvements in the BTP Manager installation area
  .gitignore
  README.md
  hack/run_module_image.sh
  hack/run_template.sh
Labels: area/documentation, size/M, lgtm

#214 fix failure when /downloaded_module dir doesnt exist
  hack/run_module_image.sh
Labels: size/XS, lgtm

#212 Formatting fixes
  README.md
Labels: size/S, area/documentation, lgtm

#224 rbac-proxy removed, BtpOperator spec nullable
  .gitignore
  api/v1alpha1/btpoperator_types.go
  config/crd/bases/operator.kyma-project.io_btpoperators.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/operator_v1alpha1_btpoperator.yaml
  hack/create_module_image.sh
Labels: size/S, lgtm

#208 Block removal of btp-operator resource if SI or SB exists
  api/v1alpha1/btpoperator_types.go
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/conditions.go
  docs/operations.md
Labels: size/L, area/documentation, lgtm

#230 Finalizer renamed, default BTP Operator CR renamed
  README.md
  config/samples/operator_v1alpha1_btpoperator.yaml
  controllers/btpoperator_controller.go
  examples/btp-operator.yaml
Labels: size/S, area/documentation, lgtm

#229 Set harddelete status when force-delete label is added during deletion
  controllers/btpoperator_controller.go
Labels: size/S, lgtm

#209 Certs
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  docs/assets/certs.drawio
  docs/assets/certs.svg
  docs/certs.md
  internal/certs/certs.go
  main.go
  module-chart/chart/templates/webhook.yml
  module-resources/apply/webhook.yml
Labels: area/documentation, size/XXL, lgtm

#233 Remove wozniakjan from codeowners
  OWNERS_ALIASES
Labels: size/XS, lgtm

#223 Exclude helm hooks from operator
  .github/workflows/auto-update.yml
  docs/workflows.md
  hack/update/make-module-resources.sh
Labels: area/documentation, size/M, lgtm

#236 Add certs.md to the list of docs
  docs/README.md
Labels: area/documentation, size/XS, lgtm

#239 Change template.yaml targets
  Makefile
  hack/release.sh
Labels: size/S, lgtm

#242 fix url
  hack/release.sh
Labels: size/XS, lgtm

#237 Update to UTC
  controllers/btpoperator_controller.go
  internal/certs/certs.go
Labels: size/S, lgtm

#202 Add unit and e2e tests to release workflow
  .github/workflows/create-release.yaml
  .github/workflows/e2e-test-k3s.yml
  .github/workflows/run-e2e-tests-reusable.yaml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-unit-tests.yaml
  Makefile
  docs/README.md
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/release.md
  docs/workflows.md
  hack/release.sh
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
  scripts/testing/k3s-setup.sh
  scripts/testing/registries.yaml
  scripts/testing/set-env-vars.sh
Labels: area/documentation, size/XL, lgtm

#248 Fixes for new release workflow
  .github/workflows/create-release.yaml
  hack/release.sh
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
Labels: size/L, lgtm

#250 Changelog removed for the time being
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#251 Token passed to await script
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
Labels: size/S, lgtm

#252 Job names shortened for release workflow
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
  scripts/create_changelog2.sh
Labels: size/M, lgtm

#254 Copy of scripts called from prow jobs - migration pre-stage
  scripts/create_module_image.sh
  scripts/release.sh
Labels: size/L, lgtm

#253 Changelog creation corrected
  .github/workflows/create-release.yaml
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
  scripts/create_changelog2.sh
Labels: size/L, lgtm

#255 Changelog file name fixed
  scripts/create_changelog.sh
Labels: size/XS, lgtm

#244 Refactor BtpOperator controller tests
  Makefile
  controllers/btpoperator_controller_certificates_test.go
  controllers/btpoperator_controller_configuration_test.go
  controllers/btpoperator_controller_deprovisioning_test.go
  controllers/btpoperator_controller_provisioning_test.go
  controllers/btpoperator_controller_test.go
  controllers/btpoperator_controller_updating_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  go.mod
  go.sum
Labels: size/XXL, lgtm

#256 Reverted change in await script
  scripts/await_artifacts.sh
Labels: size/XS, lgtm

#257 Moving scripts to new location
  hack/create_module_image.sh
  hack/release.sh
  hack/run_template.sh
  scripts/run_module_image.sh
  scripts/testing/run_e2e_module_tests.sh
Labels: size/L, lgtm
