Repository kyma-project/btp-manager, pull requests merged in 2023-07, with the labels that each got.

#337 Add annotations in pod template to bypass Istio sidecar for metrics
  config/manager/manager.yaml
Labels: size/XS, lgtm

#344 Invalid name of env variable corrected in documentation
  docs/contributor/05-10-testing.md
Labels: area/documentation, size/XS, lgtm

#336 Update resource during reconcile if resource exists
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_updating_test.go
  controllers/utils_test.go
Labels: size/L, lgtm

#345 Documentation update for https://github.com/kyma-project/btp-manager/pull/336
  docs/contributor/02-10-operations.md
Labels: area/documentation, size/XS, lgtm

#352 Adjust documentation
  docs/contributor/04-10-workflows.md
  docs/contributor/05-20-e2e_tests.md
Labels: area/documentation, size/XS, lgtm

#346 upgrade k8s version to 1.26
  scripts/testing/k3s-setup.sh
Labels: size/XS, lgtm

#351 Fix BtpOperator Status update
  api/v1alpha1/btpoperator_types.go
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
Labels: size/L, lgtm

#348 Add stres tests to release process
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  scripts/await_artifacts.sh
  scripts/testing/install.sh
  scripts/testing/run_e2e_module_tests.sh
  scripts/testing/stress-mem.sh
Labels: size/L, lgtm

#355 Add stress tests as required to release
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#356 Fix envs in the stress tests
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#358 Missing inheritance of secrets
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#359 Passing proper envs and parameters
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
Labels: size/XS, lgtm

#354 Adjust operations and certs diagrams
  docs/assets/activity_deprovisioning.drawio
  docs/assets/activity_provisioning.drawio
  docs/assets/activity_updating.drawio
  docs/assets/certs.drawio
  docs/assets/certs.svg
  docs/assets/deprovisioning.svg
  docs/assets/provisioning.svg
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/contributor/03-10-release.md
Labels: documentation, area/documentation, size/XXL, lgtm

#363 Minor fix
  docs/contributor/02-10-operations.md
Labels: area/documentation, size/XS, lgtm

#361 Add label selectors to informer's cache
  Makefile
  controllers/cache.go
  controllers/suite_test.go
  controllers/testdata/test-secret.yaml
  controllers/utils_test.go
  docs/contributor/01-20-configuration.md
  docs/contributor/02-10-operations.md
  docs/contributor/07-10-informer-cache.md
  examples/btp-manager-secret.yaml
  examples/btp-operator-configmap.yaml
  main.go
  scripts/testing/create-secrets-configmaps.sh
  scripts/testing/yaml/e2e-test-configmap.yaml
  scripts/testing/yaml/e2e-test-secret.yaml
  scripts/testing/yaml/stress-cm.yaml
  scripts/testing/yaml/stress-secret.yaml
Labels: size/L, area/documentation, lgtm
