Repository kyma-project/btp-manager, pull requests merged in 2023-06, with the labels that each got.

#304 Promote a module to internal repo
  .github/workflows/promote.yml
  scripts/python/adjust_template.py
  scripts/python/requirements.txt
Labels: size/L, lgtm

#318 Reduce the risk of OOM
  controllers/btpoperator_controller.go
  controllers/serviceinstance_controller.go
  scripts/testing/stress-mem.sh
Labels: size/M, lgtm

#322 Golang Upgrade
  Dockerfile
Labels: size/XS, lgtm

#325 Autodoc script fixed when files do not exists + metadata fix
  cmd/autodoc/main.go
  docs/operations.md
  internal/conditions/conditions.go
  scripts/autodoc/extract_conditions_data.sh
Labels: area/documentation, size/M, lgtm

#326 clean not needed metrics
  controllers/btpoperator_controller.go
  internal/metrics/metrics.go
Labels: size/S, lgtm

#323 State warning if secret is missing
  api/v1alpha1/btpoperator_types.go
  cmd/autodoc/main.go
  config/crd/bases/operator.kyma-project.io_btpoperators.yaml
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_provisioning_test.go
  docs/operations.md
  internal/conditions/conditions.go
Labels: area/documentation, size/M, lgtm

#327 Reverted to Old Monitoring Yaml Configuration
  config/default/kustomization.yaml
  config/prometheus/monitor.yaml
Labels: size/S, lgtm

#330 BTP operator CR as a release asset
  docs/installation.md
  scripts/release.sh
Labels: size/S, area/documentation, lgtm

#331 Remove rendered.yaml
  docs/release.md
  scripts/await_artifacts.sh
  scripts/release.sh
Labels: area/documentation, size/XS, lgtm

#329 Reverting Back to #305
  config/default/kustomization.yaml
  config/prometheus/monitor.yaml
Labels: size/S, lgtm
