Repository kyma-project/btp-manager, pull requests merged in 2023-05, with the labels that each got.

#277 First stage of adding credential type parameter
  .github/workflows/run-e2e-tests-reusable.yaml
Labels: size/S, lgtm

#278 Passing GITHUB_RUN_ID to underlying e2e tests for PRs
  .github/workflows/run-e2e-tests.yaml
Labels: size/XS, lgtm

#280 Determining credentials used for e2e test in release process
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#281 Duplicated `https` in BTP Operator Repo Link
  scripts/update/create_pr.sh
Labels: size/XS, lgtm

#283 Adjust release process for raw k8s yaml
  scripts/release.sh
Labels: size/XS, lgtm

#286 More logging during release process
  scripts/release.sh
Labels: size/S, lgtm

#287 Corrected parameter passing for release workflow
  .github/workflows/run-e2e-tests-reusable.yaml
Labels: size/XS, lgtm

#288 add missing err handling
  internal/certs/certs.go
Labels: size/XS, lgtm

#289 Release scripts improvements
  .github/workflows/create-release.yaml
  scripts/testing/run_e2e_module_tests.sh
Labels: size/XS, lgtm

#291 fix current dir
  hack/create-secret-file.sh
Labels: size/XS, lgtm

#284 Update and restructure BTP Manager docs
  README.md
  docs/README.md
  docs/certs.md
  docs/installation.md
  docs/lifecycle_manager.md
  docs/operations.md
Labels: size/L, area/documentation, lgtm

#293 Documentation update - E2E tests
  docs/e2e_tests.md
  docs/release.md
Labels: area/documentation, size/M, lgtm

#294 add more logs
  controllers/btpoperator_controller.go
Labels: size/XS, lgtm

#296 Change release scripts permissions
  scripts/create_draft_release.sh
  scripts/publish_release.sh
Labels: size/XS, lgtm

#298 E2E module upgrade test
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-upgrade-tests-reusable.yaml
  docs/e2e_tests.md
  docs/release.md
  scripts/testing/run_e2e_module_tests.sh
  scripts/testing/run_e2e_module_upgrade_tests.sh
  scripts/testing/yaml/e2e-test-btpoperator.yaml
  scripts/testing/yaml/e2e-test-service-binding.yaml
  scripts/testing/yaml/e2e-test-service-instance.yaml
Labels: size/L, area/documentation, lgtm

#297 metrics v1
  .gitignore
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_deprovisioning_test.go
  controllers/btpoperator_controller_provisioning_test.go
  controllers/conditions.go
  controllers/errors.go
  controllers/instnace_binding_controller_manager.go
  controllers/serviceinstance_controller.go
  controllers/serviceinstance_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/metrics/metrics.go
  main.go
Labels: size/L, lgtm

#306 update golang
  Dockerfile
  go.mod
Labels: size/XS, lgtm

#308 Context decorated with cancel for SI SB controller
  controllers/instance_binding_controller_manager.go
Labels: size/S, lgtm
