Repository kyma-project/btp-manager, pull requests merged in 2023-02, with the labels that each got.

#98 Install module from manifests without dependencies to module-manager
  .gitignore
  Dockerfile
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/conditions.go
  controllers/errors.go
  controllers/suite_test.go
  docs/configuration.md
  go.mod
  go.sum
  internal/manifest/handler.go
  internal/manifest/handler_test.go
  internal/manifest/testdata/test-manifests.yaml
  internal/manifest/testdata/test-secret.yml
  main.go
Labels: area/documentation, size/XL, lgtm

#159 improvments
  .github/workflows/auto-update.yml
  hack/update/get-latest-chart-version.sh
  hack/update/make-module-chart.sh
  hack/update/make-module-resources.sh
Labels: size/M, lgtm

#161 Update create-release.yaml
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#162 Minor corrections
  docs/README.md
  docs/workflows.md
  module-chart/README.md
Labels: size/S, area/documentation, lgtm

#163 Make proper path to kyma alpha create module command
  Makefile
Labels: size/XS, lgtm

#169 Kustomization settings
  config/default/kustomization.yaml
  testing/go/e2e_test.go
Labels: size/XS, lgtm

#170 Do not wait till btpoperator-sample is ready
  testing/go/e2e_test.go
Labels: size/S, lgtm

#164 Typos corrected in workflow description
  .github/workflows/promote.yml
  config/samples/operator_v1alpha1_btpoperator.yaml
Labels: size/S, lgtm

#167 Running module from oci image
  README.md
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  hack/run_module_image.sh
  testing/go/e2e_test.go
Labels: area/documentation, size/M, lgtm

#171 Fix docs
  README.md
Labels: area/documentation, size/XS, lgtm

#166 Module update based on manifests without dependencies to module-manager
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
  internal/manifest/handler.go
  internal/ymlutils/extractor.go
  internal/ymlutils/renamer.go
  main.go
Labels: size/XXL, lgtm

#177 Automate changelog creation
  .github/workflows/create-release.yaml
Labels: size/M, lgtm

#178 Setup test build cache
  .github/workflows/make-test.yaml
Labels: size/XS, lgtm

#179 Add fetching for tags in changelog
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#168 Put release link to the promote workflow
  .github/workflows/promote.yml
Labels: size/XS, lgtm

#180 Autogenerate RBAC from btp-operator resources
  .github/workflows/auto-update.yml
  config/rbac/role.yaml
  controllers/btpoperator_controller.go
  hack/update/make-module-resources.sh
Labels: size/L, lgtm

#181 Initial version of script building OCI module image
  hack/create_module_image.sh
Labels: size/S, lgtm

#183 Update code owners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#182 Update operations docs
  docs/assets/activity_provisioning.drawio
  docs/assets/provisioning.svg
  docs/operations.md
Labels: area/documentation, size/M, lgtm

#185 Document RBAC auto-generation process
  docs/workflows.md
Labels: area/documentation, size/XS, lgtm

#188 Use gopher group in CODEOWNERS instead of enumerating its members
  CODEOWNERS
Labels: size/XS, lgtm

#190 Additional RBAC for instances, bindings and namespaces
  config/rbac/role.yaml
  controllers/btpoperator_controller.go
Labels: size/S, lgtm

#191 Enhance timeouts for unit test on external cluster
  Makefile
  controllers/suite_test.go
  testing/set-env-vars.sh
Labels: size/M, lgtm

#193 Refactor deprovisioning to use module resources instead of chart
  controllers/btpoperator_controller.go
  docs/assets/activity_deprovisioning.drawio
  docs/assets/deprovisioning.svg
  docs/operations.md
Labels: area/documentation, size/M, lgtm
