Repository kyma-project/btp-manager, pull requests merged in 2023-08, with the labels that each got.

#364 Describe processes in points
  docs/assets/activity_deprovisioning.drawio
  docs/assets/activity_provisioning.drawio
  docs/assets/deprovisioning.svg
  docs/assets/provisioning.svg
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/contributor/02-10-operations.md
Labels: documentation, size/L, area/documentation, lgtm

#367 Use relative links in docs
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/01-20-configuration.md
  docs/contributor/02-10-operations.md
  docs/contributor/04-10-workflows.md
  docs/contributor/05-10-testing.md
  docs/contributor/05-20-e2e_tests.md
  docs/contributor/06-10-certs.md
  docs/contributor/07-10-informer-cache.md
  docs/user/02-10-usage.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, area/documentation, size/M, lgtm, docs/modularization

#368 Add OOM testing for release process
  .github/workflows/create-release.yaml
  scripts/testing/check_btp-manager_restarts.sh
  scripts/testing/create-secrets-configmaps.sh
  scripts/testing/stress-mem.sh
  scripts/testing/yaml/cm.tmpl.yaml
  scripts/testing/yaml/secret.tmpl.yaml
  scripts/testing/yaml/stress-cm.yaml
  scripts/testing/yaml/stress-secret.yaml
Labels: size/L, lgtm

#373 Decrease resource usage
  config/manager/manager.yaml
Labels: size/XS, lgtm

#374 Rename certs regenerations metric
  internal/metrics/metrics.go
Labels: size/XS, lgtm

#376 Add metrics documentation
  docs/contributor/08-10-metrics.md
Labels: size/S, area/documentation, lgtm

#357 Security scanner configuration - first step
  Makefile
  docs/contributor/03-10-release.md
  scripts/create_module_image.sh
  scripts/create_scan_config.sh
  scripts/release.sh
  scripts/testing/run_e2e_on_k3d.sh
Labels: area/documentation, size/M, lgtm

#385 Added the email id in the upstream contact name
  .reuse/dep5
Labels: size/XS, lgtm

#386 Add checking for dead links
  .github/workflows/markdown-link-check.yaml
  .mlc.config.json
  CODE_OF_CONDUCT.md
  docs/contributor/03-10-release.md
  docs/contributor/04-10-workflows.md
Labels: size/S, area/documentation, lgtm

#387 Security scan configuration for main branch - second step
  scripts/sec-scanners-config.yaml
Labels: size/XS, lgtm

#388 Schedule the dead links checking job
  .github/workflows/markdown-link-check.yaml
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/XS, lgtm

#383 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, area/documentation, lgtm

#390 Configuration file location corrected
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#391 Fix unit tests caching
  .github/workflows/run-unit-tests-reusable.yaml
Labels: size/S, lgtm

#393 Update the README file
  README.md
  docs/contributor/08-10-metrics.md
Labels: area/documentation, size/XS, lgtm

#372 Automatically generate Realase Notes by Labels
  .github/release.yml
  .github/workflows/create-release.yaml
  .github/workflows/label-validator.yml
  scripts/create_draft_release.sh
  scripts/label_validator.sh
Labels: kind/feature, size/L, area/documentation, lgtm

#395 Remove a redundant file
  LICENSE
Labels: size/L, area/documentation, lgtm, kind/enhancement

#399 Fix module build command
  Makefile
Labels: size/XS, lgtm, kind/enhancement

#397 Release candidate tag set to latest release
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/enhancement

#406 Update sec-scanners-config.yaml to 0.5.0 release
  sec-scanners-config.yaml
Labels: lgtm, kind/enhancement

#407 update go
  Dockerfile
Labels: size/XS, lgtm, kind/enhancement

#409 Rename workflows
  .github/workflows/label-validator.yml
  .github/workflows/run-unit-tests.yaml
Labels: size/XS, lgtm, kind/enhancement

#410 Security fixes
  controllers/instance_binding_controller_manager.go
  controllers/serviceinstance_controller_test.go
  controllers/suite_test.go
Labels: size/S, lgtm, kind/enhancement

#412 Revert Remove a redundant file
  LICENSE
Labels: size/L, lgtm, kind/enhancement

#413 Update sec-scanners-config.yaml (align module name with module template)
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/enhancement

#419 Module name change in dynamically create security scanning configuration file
  scripts/create_scan_config.sh
Labels: kind/bug, lgtm

#411 label validator improvements
  .github/workflows/label-validator.yml
  .gitignore
  scripts/label_validator.sh
Labels: size/M, kind/deprecation, lgtm, kind/enhancement

#421 Update create-secret-file.sh
  hack/create-secret-file.sh
Labels: size/XS, lgtm, kind/enhancement
