Repository kyma-project/btp-manager, pull requests merged in 2023-04, with the labels that each got.

#259 Moving auto-update scripts to new location
  .github/workflows/auto-update.yml
  scripts/update/get-latest-chart-version.sh
  scripts/update/make-module-chart.sh
  scripts/update/make-module-resources.sh
Labels: size/S, lgtm

#264 Do not run E2E for draft PRs
  .github/workflows/run-e2e-tests.yaml
Labels: size/XS, lgtm

#262 Unifying auto-update workflow and scripts
  .github/workflows/auto-update.yml
  scripts/create_changelog.sh
  scripts/update/create_pr.sh
  scripts/update/get-latest-chart-version.sh
  scripts/update/make-module-chart.sh
  scripts/update/make-module-resources.sh
Labels: size/L, lgtm

#266 Fixing condition to let the workflow exit if nothing to do
  .github/workflows/auto-update.yml
Labels: size/XS, lgtm

#265 Set BtpOperator CR status to ready when module deployment is ready
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_certificates_test.go
  controllers/suite_test.go
  controllers/utils_test.go
Labels: size/L, lgtm

#267 run unit test on main to build fresh cache for PRs
  .github/workflows/run-unit-tests.yaml
Labels: size/XS, lgtm

#240 React on sisb deletion
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_certificates_test.go
  controllers/instnace_binding_controller_manager.go
  controllers/serviceinstance_controller.go
  controllers/serviceinstance_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  go.mod
  go.sum
  main.go
Labels: size/L, lgtm

#274 Add raw Kubernetes YAML handling scenario for e2e-test
  scripts/check_if_k8s_yaml.sh
  scripts/run_module_image.sh
  scripts/testing/run_e2e_module_tests.sh
  scripts/uninstall_btp_manager.sh
Labels: size/M, lgtm

#272 Bump helm version
  go.mod
  go.sum
Labels: size/L, lgtm
