Repository kyma-project/btp-manager, pull requests merged in 2023-10, with the labels that each got.

#451 Add timeout before creating tag
  .github/workflows/create-release.yaml
  scripts/await_pr_merge.sh
Labels: size/XS, lgtm, kind/enhancement

#452 Add changes pull before creating tag
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement

#447 Configure dependabot
  .github/dependabot.yml
Labels: size/S, lgtm, kind/enhancement

#468 Shortened version of promote workflow
  .github/workflows/promote_to_module-manifests.yaml
Labels: lgtm, kind/enhancement

#475 Fix for new promotion pipeline
  .github/workflows/promote_to_module-manifests.yaml
Labels: kind/bug, size/S, lgtm

#476 Warning about full module name
  .github/workflows/promote_to_module-manifests.yaml
Labels: size/XS, lgtm, kind/enhancement

#479 Update dependencies
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_configuration_test.go
  controllers/cache.go
  controllers/instance_binding_controller_manager.go
  controllers/serviceinstance_controller.go
  controllers/suite_test.go
  controllers/utils_test.go
  go.mod
  go.sum
  main.go
Labels: size/L, lgtm, kind/enhancement

#482 Revert "Bump sec-scanners-config.yaml to 1.0.1 (#481)"
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/enhancement

#483 Fix commit refs during release
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, kind/enhancement

#487 Fix a link
  docs/contributor/03-10-release.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement
