Repository kyma-project/btp-manager, pull requests merged in 2023-09, with the labels that each got.

#426 Add sec-scanner-bump to release workflow
  .github/workflows/create-release.yaml
  scripts/await_pr_merge.sh
  scripts/create_scan_config.sh
  scripts/create_sec_scanner_bump_pr.sh
Labels: size/L, lgtm, kind/enhancement

#429 Add additional scan config option to script
  .github/workflows/create-release.yaml
  scripts/create_scan_config.sh
Labels: size/M, lgtm, kind/enhancement

#431 Documentation update - correction
  docs/contributor/05-20-e2e_tests.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#433 Script extraction for building images locally
  scripts/build_and_push_locally.sh
  scripts/testing/run_e2e_on_k3d.sh
Labels: size/M, lgtm, kind/enhancement

#432 Update release workflow docs
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/contributor/03-10-release.md
Labels: size/L, area/documentation, lgtm, kind/enhancement

#439 Change the module name
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/02-10-operations.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: size/S, area/documentation, lgtm, kind/enhancement

#445 Add a security policy (SECURITY.md)
  SECURITY.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement
