Repository kyma-project/btp-manager, pull requests merged in 2023-12, with the labels that each got.

#521 Run name added to create release workflow
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#519 Replace release label validator script
  .github/workflows/create-release.yaml
  scripts/python/release_label_validator.py
  scripts/python/requirements.txt
  scripts/testing/run_e2e_module_upgrade_tests.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#525 top pod for sap btp service operator
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#527 Pipelines improvements
  .github/workflows/create-release.yaml
  scripts/testing/check_btp-manager_restarts.sh
  scripts/testing/check_pod_restarts.sh
  scripts/testing/check_top.sh
  scripts/testing/stress-mem-instances-bindings.sh
  scripts/testing/stress-mem-secrets-configmaps.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#528 update priviliges
  scripts/testing/check_top.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#532 Fix not ready metrics by polling
  scripts/testing/check_top.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#534 pipeline improvements
  .github/workflows/create-release.yaml
  scripts/testing/stress-mem-instances-bindings.sh
  scripts/testing/stress-mem-secrets-configmaps.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#535 0.5.6 service operator updates
  .gitignore
  docs/user/02-10-usage.md
  hack/create-secret-file.sh
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#536 Update ginkgo to v2.13.2 in makefile
  Makefile
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#538 Update deps 211223
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#547 Use technical names consistently
  docs/contributor/05-20-e2e_tests.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes
