Repository kyma-project/btp-manager, pull requests merged in 2023-01, with the labels that each got.

#83 update test and k3s version
  .github/workflows/e2e-test-k3s.yml
  operator/main.go
  testing/go/e2e_test.go
  testing/go/go.mod
  testing/go/go.sum
  testing/k3s-setup.sh
Labels: size/XL, lgtm

#84 Remove the chart
  .gitignore
  charts/btp-manager/Chart.yaml
  charts/btp-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_btpoperators.operator.kyma-project.io.yaml
  charts/btp-manager/templates/apps_v1_deployment_btp-manager-controller-manager.yaml
  charts/btp-manager/templates/monitoring.coreos.com_v1_servicemonitor_btp-manager-controller-manager-metrics-monitor.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrole_btp-manager-manager-role.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrole_btp-manager-metrics-reader.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrole_btp-manager-proxy-role.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_btp-manager-manager-rolebinding.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_btp-manager-proxy-rolebinding.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_role_btp-manager-leader-election-role.yaml
  charts/btp-manager/templates/rbac.authorization.k8s.io_v1_rolebinding_btp-manager-leader-election-rolebinding.yaml
  charts/btp-manager/templates/v1_namespace_btp-manager-system.yaml
  charts/btp-manager/templates/v1_service_btp-manager-controller-manager-metrics-service.yaml
  charts/btp-manager/templates/v1_serviceaccount_btp-manager-controller-manager.yaml
Labels: size/L, lgtm

#87 Fix tests
  operator/controllers/btpoperator_controller_test.go
Labels: size/M, lgtm

#90 Update test fix
  .gitignore
  operator/controllers/btpoperator_controller_test.go
Labels: size/XS, lgtm

#91 Add temporary files to gitignore
  .gitignore
Labels: size/XS, lgtm

#89 Promote to Channel pipeline
  .github/workflows/promote.yml
  docs/workflows.md
Labels: size/L, area/documentation, lgtm

#96 Prepare release script
  Makefile
  hack/release.sh
Labels: size/M, lgtm

#101 wip
  hack/release.sh
Labels: size/XS, lgtm

#94 Make test executions not share resources
  .gitignore
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
Labels: size/L, area/documentation, lgtm

#102 Test 0.0.2 1
  hack/release.sh
Labels: size/XS, lgtm

#104 fix makefile
  hack/release.sh
Labels: size/XS, lgtm

#95 Wrap function calls inside `Eventually()`
  controllers/btpoperator_controller_test.go
Labels: size/M, lgtm

#109 wip
  hack/release.sh
Labels: size/XS, lgtm

#108 Timeout unit tests after 30s
  Makefile
Labels: size/XS, lgtm

#110 Download proper kyma cli
  Makefile
  hack/get_kyma_file_name.sh
Labels: size/M, lgtm

#111 wip
  hack/get_kyma_file_name.sh
Labels: size/XS, lgtm

#112 wip
  Makefile
Labels: size/XS, lgtm

#113 a change
  Makefile
Labels: size/XS, lgtm

#93 Real cluster option and labelling
  Makefile
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
  docs/README.md
  docs/assets/environment-variable-for-test-run-config.png
  docs/assets/test-run-configuration.png
  docs/testing.md
  go.mod
  go.sum
  testing/set-env-vars.sh
Labels: size/L, area/documentation, lgtm

#114 wip
  Makefile
Labels: size/XS, lgtm

#116 wip
  hack/release.sh
Labels: size/XS, lgtm

#99 Replace polling with watch
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
Labels: size/L, lgtm

#117 change release..sh
  hack/release.sh
Labels: size/XS, lgtm

#119 Update to new GH user
  .github/workflows/promote.yml
Labels: size/S, lgtm

#122 Make-release script
  hack/release.sh
Labels: size/M, lgtm

#123 E2E Test Correction
  config/rbac/role.yaml
  controllers/btpoperator_controller.go
  testing/go/e2e_test.go
Labels: size/M, lgtm

#125 Release process
  .github/workflows/create-release.yaml
Labels: size/M, lgtm

#126 Create release branch
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#127 Fix release action
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#128 Release process
  Makefile
  hack/get_kyma_file_name.sh
  hack/release.sh
Labels: size/L, lgtm

#131 Release Pipeline Fixes
  Makefile
  hack/release.sh
Labels: size/XS, lgtm

#132 Release without branch
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#133 Corrections and improvements
  docs/README.md
  docs/configuration.md
  docs/operations.md
  docs/workflows.md
  module-chart/README.md
Labels: area/documentation, size/M, lgtm

#137 Put instructions in lists
  module-chart/README.md
Labels: documentation, area/documentation, size/M, lgtm

#138 Prepare structure for update pipeline
  .gitignore
  controllers/btpoperator_controller.go
  controllers/suite_test.go
  docs/configuration.md
  examples/btp-operator-configmap.yaml
  module-chart/chart/.helmignore
  module-chart/chart/Chart.yaml
  module-chart/chart/README.md
  module-chart/chart/templates/cert-manager-certificate.yml
  module-chart/chart/templates/cert-manager-issuer.yml
  module-chart/chart/templates/configmap.yml
  module-chart/chart/templates/crd.yml
  module-chart/chart/templates/deployment.yml
  module-chart/chart/templates/gardener-cert-manager-certificate.yml
  module-chart/chart/templates/gardener-cert-manager-issuer-secret.yml
  module-chart/chart/templates/gardener-cert-manager-issuer.yml
  module-chart/chart/templates/rbac.yml
  module-chart/chart/templates/secret-tls.yml
  module-chart/chart/templates/secret.yml
  module-chart/chart/templates/service.yml
  module-chart/chart/templates/webhook.yml
  module-chart/chart/values.yaml
  module-chart/overrides.yaml
Labels: size/S, area/documentation, lgtm

#140 Module restructure
  module-chart/README.md
Labels: area/documentation, size/XS, lgtm

#141 Module restructure
  module-chart/README.md
Labels: area/documentation, size/M, lgtm

#142 change filename
  .github/workflows/promote.yml
Labels: size/XS, lgtm

#147 Change message in workflow, update docs, pass namespace
  .github/workflows/auto-update.yml
  docs/workflows.md
  hack/update/make-module-resources.sh
Labels: size/S, area/documentation, lgtm
