Repository kyma-project/btp-manager, pull requests merged in 2024-04, with the labels that each got.

#644 Update the README files
  README.md
  docs/user/02-20-examples.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#647 Documentation update about credentials rotation
  docs/contributor/05-20-e2e_tests.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#655 Get Secrets for Service Manager
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_cr_rotation_test.go
  controllers/btpoperator_controller_deprovisioning_test.go
  controllers/serviceinstance_controller.go
  controllers/serviceinstance_controller_test.go
  controllers/utils_test.go
  internal/cluster-object/namespace_provider.go
  internal/cluster-object/namespace_provider_test.go
  internal/cluster-object/object_provider.go
  internal/cluster-object/secret_provider.go
  internal/cluster-object/secret_provider_test.go
  internal/cluster-object/service_instance_provider.go
  internal/cluster-object/service_instance_provider_test.go
Labels: area/documentation, size/XL, lgtm, kind/enhancement, cla: yes

#669 Add gitleaks workflow
  .github/workflows/pull-gitleaks.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#672 Enhance release workflow
  .github/workflows/create-release.yaml
  scripts/upload_assets.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#671 Ignore PRs not Merged to Main
  scripts/python/release_label_validator.py
Labels: kind/bug, size/XS, lgtm, cla: yes

#657 Change Deleting to Warning for ServiceInstancesAndBindingsNotCleaned reason
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_cr_rotation_test.go
  controllers/btpoperator_controller_deprovisioning_test.go
  controllers/serviceinstance_controller_test.go
  docs/contributor/02-10-operations.md
  internal/conditions/conditions.go
  scripts/testing/run_e2e_module_tests.sh
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#677 Adjust GitHub ctions for sm-integration branch
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/run-go-linter.yaml
  .github/workflows/run-govulncheck.yaml
  .github/workflows/run-unit-tests.yaml
  .github/workflows/sync-with-main.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#678 Fix Sync with main workflow
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#679 Fix Sync with main workflow - running from other branches
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#680 Fix Sync with main workflow - add step to configure git user
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#681 Fix Sync with main - push changes with --force-with-lease to sync after rebasing
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#682 Fix Sync with main - use token from gopher bot for git actions
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#683 Fix Sync with main - fix vars and envs in steps
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#684 Fix Sync with main - credentials setup for git
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#686 Bump sigs.k8s.io/controller-runtime from 0.17.3 to 0.18.0
  Makefile
  controllers/btpoperator_controller.go
  controllers/utils_test.go
  go.mod
  go.sum
Labels: size/L, lgtm, kind/enhancement, cla: yes
