Repository kyma-project/btp-manager, pull requests merged in 2024-03, with the labels that each got.

#623 Fix issues reported by golangci
  .github/workflows/run-go-linter.yaml
  .golangci.yml
  Makefile
  controllers/btpoperator_controller_updating_test.go
  main.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#625 Add govulncheck action
  .github/workflows/run-govulncheck.yaml
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#628 Remove govulncheck action
  .github/workflows/run-govulncheck.yaml
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#629 Alert Slack when the auto update workflow is not successful
  .github/workflows/auto-update.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#631 Dependabot changes
  Dockerfile
  go.mod
  go.sum
Labels: size/M, lgtm, kind/enhancement, cla: yes

#640 Add govulncheck
  .github/workflows/run-govulncheck.yaml
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#643 Examples of Using Secret Template
  docs/user/02-11-examples.md
  docs/user/_sidebar.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes
