Repository kyma-project/btp-manager, pull requests merged in 2024-07, with the labels that each got.

#748 Remove not needed job from image build workflow
  .github/workflows/pull-btp-manager-build-ga.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#750 Add experimental release workflow with new image builder
  .github/workflows/create-release-without-prow.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#751 Fix used envs in experimental workflow
  .github/workflows/create-release-without-prow.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#753 enable_limited_cache reverted and set in the correct way to false
  module-chart/overrides.yaml
  module-resources/apply/configmap.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#755 Bump Go to 1.22.5
  go.mod
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#735 Handle Service Bindings in SM client and get Service Instances in API
  go.mod
  internal/api/api.go
  internal/api/requests/converters.go
  internal/api/requests/requests.go
  internal/api/responses/converters.go
  internal/api/responses/responses.go
  internal/cluster-object/secret_provider.go
  internal/service-manager/client.go
  internal/service-manager/client_test.go
  internal/service-manager/testdata/service_bindings.json
  internal/service-manager/types/requests/CreateServiceBindingRequestPayload.go
  internal/service-manager/types/service_binding.go
  internal/service-manager/types/service_instance.go
Labels: size/XL, lgtm, cla: yes

#746 Loading Service Instances in BTP Manager UI Backend - API
  go.mod
  go.sum
  internal/api/api.go
  internal/api/api_test.go
  internal/api/responses/converters_test.go
  internal/api/testdata/list-instances-happy-expected.json
  internal/cluster-object/automock/provider.go
  internal/cluster-object/secret_provider.go
  internal/service-manager/automock/client.go
  internal/service-manager/client.go
  internal/service-manager/types/service_instance.go
  main.go
Labels: area/documentation, size/XL, lgtm, kind/enhancement, cla: yes

#757 Service Bindings API
  internal/api/api.go
  internal/api/requests/converters.go
  internal/api/requests/requests.go
  internal/api/responses/converters.go
  internal/api/responses/responses.go
  internal/service-manager/automock/client.go
  internal/service-manager/client.go
  internal/service-manager/types/requests/CreateServiceBindingRequestPayload.go
Labels: size/L, lgtm, kind/enhancement, cla: yes

#763 Possibility to Load Test Data Based on Env Variable
  ui/.env.development
  ui/.env.production
  ui/src/components/ServiceInstancesView.tsx
  ui/src/test-data/serivce-instances.json
Labels: size/M, lgtm, kind/enhancement, cla: yes

#766 Removal of Recursive Invocation
  ui/src/components/View.tsx
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#767 Removal of Unnecessary Body Elemenet
  ui/src/App.tsx
  ui/src/components/ServiceOfferingsView.tsx
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#768 ServiceInstanceDetailsView - UI Dialog Mechanics
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/test-data/serivce-instances.json
Labels: size/L, lgtm, kind/enhancement, cla: yes

#758 Service Instances API
  internal/api/api.go
  internal/api/api_test.go
  internal/api/requests/requests.go
  internal/api/responses/converters.go
  internal/api/responses/responses.go
  internal/api/testdata/list-instances-happy-expected.json
  internal/cluster-object/automock/provider.go
  internal/cluster-object/fake.go
  internal/cluster-object/object_provider.go
  internal/cluster-object/secret_provider.go
  internal/service-manager/automock/client.go
  internal/service-manager/client.go
  internal/service-manager/client_test.go
  internal/service-manager/fake.go
  internal/service-manager/types/common.go
  main.go
  ui/src/components/ServiceInstancesView.tsx
Labels: size/XXL, lgtm, cla: yes

#769 Rename fields and tags in API structs according to Service Manager objects
  internal/api/api.go
  internal/api/api_test.go
  internal/api/requests/converters.go
  internal/api/requests/requests.go
  internal/api/responses/responses.go
Labels: size/M, lgtm, cla: yes

#770 Simple Create Instance Form
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes

#774 UI Corrections
  ui/public/index.html
  ui/src/App.css
  ui/src/App.tsx
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/components/View.tsx
  ui/src/index.css
  ui/src/index.tsx
  ui/src/shared/models.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes
