Repository kyma-project/btp-manager, pull requests merged in 2024-02, with the labels that each got.

#606 Remove last k3s versions input from release
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#604 Apply flexible alerts plugin
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/02-10-operations.md
  docs/contributor/03-10-release.md
  docs/contributor/04-10-workflows.md
  docs/contributor/05-10-testing.md
  docs/contributor/06-10-certs.md
  docs/contributor/07-10-informer-cache.md
  docs/user/02-10-usage.md
  docs/user/README.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#608 Fix indentation in the alerts
  README.md
  docs/user/02-10-usage.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#611 Add job skipping to workflows
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests-reusable.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-unit-tests.yaml
Labels: size/L, lgtm, kind/enhancement, cla: yes

#616 Update workflow docs
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#619 Update dependencies
  go.mod
  go.sum
Labels: size/L, lgtm, kind/enhancement, cla: yes
