Repository kyma-project/btp-manager, pull requests merged in 2024-06, with the labels that each got.

#713 Removed Redundant Description
  api/v1alpha1/btpoperator_types.go
Labels: kind/bug, size/XS, lgtm, cla: yes

#717 Service Manager client - get Service Offering details and plans
  internal/service-manager/client.go
  internal/service-manager/client_test.go
  internal/service-manager/testdata/service_plans.json
  internal/service-manager/types/service_offering.go
  internal/service-manager/types/service_plan.go
Labels: size/XL, lgtm, cla: yes

#719 Test multiple btpOperators reconciliation
  scripts/testing/multiple_btpoperators_exist.sh
  scripts/testing/run_e2e_module_tests.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#725 Change OlderCRExists state from error to warning
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_cr_rotation_test.go
  docs/contributor/02-10-operations.md
  internal/conditions/conditions.go
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#720 Run frontend from go binary
  Dockerfile
  Makefile
  config/manager/manager.yaml
  docs/contributor/09-10-ui.md
  go.mod
  go.sum
  internal/api/api.go
  main.go
  ui/src/components/SecretsView.tsx
  ui/src/shared/api.tsx
  ui/src/shared/validator.tsx
  ui/web.go
Labels: size/L, area/documentation, lgtm, cla: yes

#731 Adjust resources readiness(ReadyTimeout, ReadyCheckInterval) for slow clusters
  controllers/btpoperator_controller.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#736 Add image builder workflow
  .github/workflows/pull-btp-manager-build-ga.yaml
Labels: size/M, lgtm, kind/enhancement, cla: yes

#737 Improve the image build workflow
  .github/workflows/pull-btp-manager-build-ga.yaml
  Dockerfile.ga
Labels: size/M, lgtm, kind/enhancement, cla: yes

#741 Enable Limited Cache
  module-resources/apply/configmap.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#743 Bump Go to 1.22.4
  go.mod
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#745 Update Dockerfile.ga to use --chown flag for file copying
  Dockerfile.ga
Labels: size/XS, lgtm, kind/enhancement, cla: yes
