Repository kyma-project/btp-manager, pull requests merged in 2024-12, with the labels that each got.

#914 Exclude pre-releases while fetching latest `k3s` versions
  scripts/testing/get-latest-k3s-releases.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#915 Update the user docs to the HP version
  README.md
  docs/user/03-10-preconfigured-secret.md
  docs/user/03-20-multitenancy.md
  docs/user/03-21-instance-level-mapping.md
  docs/user/03-22-namespace-level-mapping.md
  docs/user/03-30-create-instances-and-bindings.md
  docs/user/03-30-management-of-service-instances-and-bindings.md
  docs/user/03-40-service-binding-rotation.md
  docs/user/03-50-formatting-service-binding-secret.md
  docs/user/03-60-pass-parameters.md
  docs/user/03-70-delete-bindings-and-instances.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: area/documentation, size/XL, kind/enhancement, cla: yes

#922 Fix a link
  docs/user/_sidebar.md
Labels: area/documentation, size/XS, kind/enhancement, cla: yes

#923 Fix tabs
  docs/user/03-21-instance-level-mapping.md
  docs/user/03-30-create-instances-and-bindings.md
  docs/user/03-70-delete-bindings-and-instances.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#929 Dependabot changes aggregated
  go.mod
  go.sum
Labels: size/M, kind/enhancement, cla: yes

#930 `skip-reconciliaton` label documentation update
  docs/user/03-10-preconfigured-secret.md
Labels: area/documentation, size/XS, kind/enhancement, cla: yes

#924 Watch sap-btp-operator-controller-manager
  controllers/btpoperator_controller.go
  scripts/testing/run_e2e_module_tests.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#934 Improve error reasons on btpOperator
  controllers/btpoperator_controller.go
Labels: size/M, lgtm, kind/enhancement, cla: yes

#940 Fix E2E test on release
  scripts/testing/run_e2e_module_tests.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#944 Security fix
  go.mod
  go.sum
Labels: kind/feature, size/XS, cla: yes

#935 E2E BTP Manager secret customization test
  .github/workflows/create-release.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/run-e2e-sap-btp-manager-secret-customization-test-reusable.yaml
  .github/workflows/run-e2e-sap-btp-manager-secret-customization-test.yaml
  docs/contributor/04-10-workflows.md
  scripts/testing/run_e2e_sap_btp_manager_secret_test.sh
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes
