Repository kyma-project/btp-manager, pull requests merged in 2024-09, with the labels that each got.

#856 Fix suffix generating and secret recreate UI state changes
  docs/contributor/09-10-ui.md
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
Labels: size/S, area/documentation, lgtm, cla: yes

#857 Closing Message Strip
  docs/contributor/09-10-ui.md
  ui/src/components/StatusMessage.tsx
Labels: kind/bug, area/documentation, size/M, lgtm, cla: yes

#858 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement, cla: yes

#860 Add a priorityClass to btp manager
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/priority-class/btp_manager_priority_class.yaml
  config/priority-class/kustomization.yaml
  controllers/testdata/test-priorityclass.yaml
  controllers/utils_test.go
  deployments/prerequisites.yaml
  docs/contributor/02-10-operations.md
  module-chart/overrides.yaml
  module-resources/apply/deployment.yml
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#868 Fix links in _sidebar.md
  docs/user/_sidebar.md
Labels: kind/bug, documentation, size/S, area/documentation, lgtm, cla: yes

#869 Update tutorial titles in sidebar
  docs/user/_sidebar.md
Labels: area/documentation, lgtm, kind/enhancement, cla: yes

#872 Add enable auto merge workflow
  .github/workflows/auto-merge.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#873 Add email to auto merge workflow
  .github/workflows/auto-merge.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#875 Add tide alternative
  .github/workflows/label-validator.yml
  .github/workflows/pr-checks.yaml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#876 Check hold labels in label validator
  .github/workflows/pr-checks.yaml
  scripts/label_validator.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#877 Add path filtering to workflows
  .github/workflows/create-release.yaml
  .github/workflows/pull-btp-manager-build.yaml
  .github/workflows/run-e2e-tests-reusable.yaml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests-reusable.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests.yaml
  .github/workflows/run-go-linter.yaml
  .github/workflows/run-govulncheck.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  .github/workflows/run-unit-tests.yaml
Labels: size/L, kind/enhancement, cla: yes

#879 Update workflow docs
  docs/contributor/04-10-workflows.md
Labels: area/documentation, size/M, kind/enhancement, cla: yes
