Repository kyma-project/btp-manager, pull requests merged in 2024-10, with the labels that each got.

#880 feat: Add proper categories for CRDs
  api/v1alpha1/btpoperator_types.go
  config/crd/bases/operator.kyma-project.io_btpoperators.yaml
Labels: size/M, kind/enhancement, cla: yes

#883 Improve the docs on creating Secrets
  README.md
  docs/assets/access_configuration.drawio.svg
  docs/assets/secrets_precedence_4.drawio.svg
  docs/user/03-00-create-btp-manager-secret.md
  docs/user/03-05-install-module.md
  docs/user/03-10-preconfigured-secret.md
  docs/user/03-20-multitenancy.md
  docs/user/03-21-create-service-instance-with-custom-secret.md
  docs/user/03-22-create-service-instance-with-namespace-based-secret.md
  docs/user/03-30-management-of-service-instances-and-bindings.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/tutorials/04-20-create-btp-service-operator-secret.md
  docs/user/tutorials/04-50-create-service-instance-with-custom-secret.md
  docs/user/tutorials/README.md
Labels: area/documentation, size/XXL, lgtm, kind/enhancement, cla: yes

#885 Fix namespace
  docs/user/03-22-create-service-instance-with-namespace-based-secret.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement, cla: yes

#886 Rebuild image
  docs/contributor/09-10-ui.md
Labels: area/documentation, size/XS, lgtm, cla: yes
