Repository kyma-project/btp-manager, pull requests merged in 2024-08, with the labels that each got.

#772 Add secrets operations related to Service Bindings in API
  internal/api/api.go
  internal/api/api_test.go
  internal/api/requests/converters.go
  internal/api/responses/converters.go
  internal/cluster-object/fake.go
  internal/cluster-object/labels.go
  internal/cluster-object/namespace_provider.go
  internal/cluster-object/namespace_provider_test.go
  internal/cluster-object/object_manager.go
  internal/cluster-object/object_provider.go
  internal/cluster-object/secret_manager.go
  internal/cluster-object/secret_manager_test.go
  internal/cluster-object/secret_provider_test.go
  internal/cluster-object/service_instance_provider.go
  internal/cluster-object/service_instance_provider_test.go
  internal/service-manager/client_test.go
  internal/service-manager/fake.go
  internal/service-manager/types/common.go
  internal/service-manager/types/service_binding.go
  internal/service-manager/types/service_instance.go
  main.go
Labels: size/XXL, lgtm, cla: yes

#778 React Router
  package-lock.json
  package.json
  ui/package.json
  ui/src/App.tsx
  ui/src/components/Layout.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/View.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes

#780 Polishing List Instances View
  ui/src/App.tsx
  ui/src/components/ServiceInstancesView.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes

#781 Create Binding Form
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/StatusMessage.tsx
  ui/src/shared/models.tsx
  ui/src/test-data/service-bindings.json
Labels: size/L, lgtm, cla: yes

#782 Addition of Labels and Parameters Consumption in Create Instance Form
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/shared/models.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes

#784 Bindings Removal
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
Labels: size/L, lgtm, cla: yes

#786 Nil Check when Removing Secrets
  internal/api/api_test.go
  internal/cluster-object/secret_manager.go
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
Labels: area/documentation, size/M, lgtm, cla: yes

#785 Update of SM Integration Docs to the Newest PR
  docs/contributor/09-10-ui.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement, cla: yes

#779 BTP Manager API - error handling
  internal/api/api.go
  internal/api/api_test.go
  internal/service-manager/client.go
  internal/service-manager/fake.go
  internal/service-manager/types/error.go
Labels: size/XL, lgtm, cla: yes

#789 Increase RSA key size
  internal/certs/certs.go
  module-chart/overrides.yaml
  module-resources/apply/deployment.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#787 Corrected Export Command Placement
  docs/contributor/09-10-ui.md
Labels: kind/bug, area/documentation, size/M, lgtm, cla: yes

#792 New Subpaths for UI
  internal/api/api.go
Labels: kind/bug, size/XS, lgtm, cla: yes

#794 Set secret name and namespace from create Service Binding request
  internal/api/api.go
  internal/api/api_test.go
  internal/api/requests/requests.go
  internal/service-manager/fake.go
Labels: size/L, lgtm, cla: yes

#797 ShellBar Corrections
  ui/src/components/Layout.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/index.css
Labels: size/L, lgtm, kind/enhancement, cla: yes

#798 Secret Name and Namespace in CreateBindingForm
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/shared/models.tsx
  ui/src/test-data/service-bindings.json
Labels: size/L, lgtm, kind/enhancement, cla: yes

#799 Dialog and StatusMessage Mechanics Corrections
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/StatusMessage.tsx
Labels: size/L, lgtm, kind/enhancement, cla: yes

#800 Updated Docs to PR-799
  docs/contributor/09-10-ui.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#801 Use internal docker registry in k3s-setup
  Dockerfile
  Dockerfile.ga
  scripts/testing/k3s-setup.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#802 Secret availability in Service Binding
  internal/api/api.go
  internal/api/api_test.go
  internal/api/responses/converters.go
  internal/api/responses/responses.go
  internal/cluster-object/fake.go
  internal/cluster-object/labels.go
  internal/service-manager/testdata/service_bindings.json
  ui/src/components/SecretsView.tsx
Labels: size/L, lgtm, cla: yes

#803 Missing FormItems for Status Messages, API Model Naming Conventions and Fixes for List Addition/Removal
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/shared/models.tsx
  ui/src/test-data/service-bindings.json
Labels: size/L, lgtm, kind/enhancement, cla: yes

#810 Set isOpen to false after closing the menu
  ui/src/components/SecretsView.tsx
Labels: size/XS, lgtm, cla: yes

#812 Fix secret operations in Service Binding related requests
  internal/api/api.go
  internal/api/requests/converters.go
  internal/api/responses/converters.go
  internal/cluster-object/secret_manager.go
  internal/cluster-object/secret_manager_test.go
Labels: size/M, lgtm, cla: yes

#809 Load secrets onClick
  ui/src/App.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceInstancesView.tsx
Labels: size/L, lgtm, cla: yes

#816 Default Bindings Value if No Content API Response
  ui/src/components/ServiceBindingsList.tsx
Labels: kind/bug, size/XS, lgtm, cla: yes

#817 Page Title
  ui/src/App.tsx
  ui/src/components/Layout.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/index.css
Labels: size/L, lgtm, kind/enhancement, cla: yes

#820 Broken Connectivity Error Page
  ui/src/components/Layout.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/index.css
Labels: size/L, lgtm, kind/enhancement, cla: yes

#821 Illustrated Message Placement and Size Corrections
  ui/src/components/ServiceBindingsList.tsx
Labels: kind/bug, size/XS, lgtm, cla: yes

#824 Corrected Bindings List Refresh
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/index.css
Labels: size/M, lgtm, kind/enhancement, cla: yes

#826 Fix create Service Binding when secret exists
  go.mod
  go.sum
  internal/api/api.go
  internal/api/api_test.go
  internal/cluster-object/fake.go
  internal/cluster-object/secret_manager.go
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#825 Show secret connection status to SM
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsView.tsx
Labels: size/M, lgtm, cla: yes

#829 Update dependencies and tools
  Makefile
  controllers/serviceinstance_controller.go
  go.mod
  go.sum
Labels: size/L, lgtm, kind/enhancement, cla: yes

#828 BTP Manager do not use prow for building images
  .github/workflows/create-release-without-prow.yaml
  .github/workflows/create-release.yaml
  .github/workflows/pull-btp-manager-build.yaml
  Dockerfile
  Dockerfile.ga
Labels: size/L, lgtm, kind/enhancement, cla: yes

#838 Update Dockerfile
  Dockerfile
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#835 Update release documentation
  docs/assets/release.drawio
  docs/assets/release.drawio.svg
  docs/assets/release.svg
  docs/contributor/03-10-release.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#840 Add hint to press Enter when adding labels to SI
  docs/contributor/09-10-ui.md
  ui/src/components/CreateInstanceForm.tsx
Labels: area/documentation, size/XS, lgtm, cla: yes

#842 Update codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#841 Fix Markdown
  docs/contributor/03-10-release.md
Labels: area/documentation, size/XS, lgtm, kind/enhancement, cla: yes

#846 Removal of Unnecessary Error Banner
  docs/contributor/09-10-ui.md
Labels: kind/bug, area/documentation, size/XS, lgtm, cla: yes

#847 Unnecessary Error
  docs/contributor/09-10-ui.md
  ui/src/components/ServiceInstancesView.tsx
Labels: kind/bug, area/documentation, size/XS, lgtm, cla: yes

#843 Restore missing Secret for existing Service Binding
  docs/contributor/09-10-ui.md
  internal/api/api.go
  internal/api/api_test.go
Labels: size/L, area/documentation, lgtm, cla: yes

#845 Api State Removal - UI Passing Secret Name and Namespace Params
  docs/contributor/09-10-ui.md
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/shared/common.tsx
  ui/src/shared/models.tsx
Labels: kind/bug, size/L, area/documentation, lgtm, cla: yes

#849 Corrected Secret Name and Namespace Params
  docs/contributor/09-10-ui.md
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/CreateInstanceForm.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
Labels: kind/bug, area/documentation, size/M, lgtm, cla: yes

#844 Api State Removal - backend
  docs/contributor/09-10-ui.md
  internal/api/api.go
  internal/api/api_test.go
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/SecretsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
Labels: size/L, area/documentation, lgtm, cla: yes

#850 Flexible Column Layout for Offerings and Instances Views
  docs/contributor/09-10-ui.md
  ui/src/components/CreateBindingForm.tsx
  ui/src/components/ServiceBindingsList.tsx
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
  ui/src/components/ServiceOfferingsDetailsView.tsx
  ui/src/components/ServiceOfferingsView.tsx
  ui/src/components/StatusMessage.tsx
  ui/src/index.css
Labels: kind/feature, size/L, area/documentation, lgtm, cla: yes

#853 Corrected Error Rendering
  docs/contributor/09-10-ui.md
  ui/src/components/ServiceInstancesDetailsView.tsx
  ui/src/components/ServiceInstancesView.tsx
Labels: kind/bug, area/documentation, size/M, lgtm, cla: yes
