Repository kyma-project/btp-manager, pull requests merged in 2024-01, with the labels that each got.

#552 Setup go environment for auto update
  .github/workflows/auto-update.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#555 Add alert to slack if auto update job will fail
  .github/workflows/auto-update.yml
Labels: size/S, lgtm, kind/enhancement, cla: yes

#556 Remove promote to channel workflow
  .github/workflows/promote.yml
  scripts/python/adjust_template.py
  scripts/python/requirements.txt
Labels: size/L, lgtm, kind/enhancement, cla: yes

#554 Fix flaky tests
  Makefile
  controllers/suite_test.go
  scripts/testing/set-env-vars.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#561 send slack msg only if token is set
  .github/workflows/auto-update.yml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#564 New target added to Makefile
  Makefile
Labels: size/S, lgtm, kind/enhancement, cla: yes

#565 Script uploading release assets
  scripts/upload_release_assets.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#572 Setting proper image and checking manifest during release
  .github/workflows/create-release.yaml
  Makefile
  scripts/upload_assets.sh
  scripts/upload_release_assets.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#571 Revert scan config file changes
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#573 File permissions corrected for script uploading assets
  scripts/upload_assets.sh
Labels: lgtm, kind/enhancement, cla: yes

#575 Documentation update after removal of `kyma CLI` invocations
  docs/assets/release.drawio
  docs/assets/release.svg
  docs/contributor/03-10-release.md
  docs/contributor/04-10-workflows.md
  docs/contributor/05-20-e2e_tests.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#574 Cleaning obsolete scripts after kyma CLI invocations removal
  Makefile
  hack/run_template.sh
  scripts/await_image.sh
  scripts/await_pr_merge.sh
  scripts/build_and_push_locally.sh
  scripts/check_artifacts_existence.sh
  scripts/check_if_k8s_yaml.sh
  scripts/create_module_image.sh
  scripts/release.sh
  scripts/run_module_image.sh
  scripts/testing/run_e2e_on_k3d.sh
  scripts/uninstall_btp_manager.sh
  scripts/upload_assets.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes

#582 Tools update changes
  Dockerfile
  go.mod
  go.sum
Labels: size/L, lgtm, kind/enhancement, cla: yes

#549 Improve the usage documentation
  docs/user/02-10-usage.md
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes, 2024-Q1

#588 update docs
  docs/user/02-10-usage.md
Labels: size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#589 Installation docs update
  Makefile
  docs/contributor/01-10-installation.md
  hack/local-template.sh
  hack/run_lifecycle_manager.sh
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#590 Utility script added
  scripts/build_push_deploy.sh
Labels: size/M, lgtm, kind/enhancement, cla: yes

#593 Update a section link
  docs/contributor/06-10-certs.md
Labels: kind/bug, area/documentation, size/XS, lgtm, cla: yes

#595 Add version validation
  .github/workflows/create-release.yaml
  docs/contributor/03-10-release.md
  scripts/python/release_label_validator.py
Labels: area/documentation, lgtm, kind/enhancement, cla: yes

#597 Release scripts corrected
  scripts/testing/install_module.sh
  scripts/testing/run_e2e_module_tests.sh
Labels: size/S, lgtm, kind/enhancement, cla: yes

#596 Reconcile resources while BtpOperator CR is in Deleting state
  controllers/btpoperator_controller.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#591 E2E Upgrade Module Test when BtpOperator CR is in Deleting state
  .github/workflows/create-release.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests-reusable.yaml
  .github/workflows/run-e2e-upgrade-while-deleting-tests.yaml
  scripts/testing/install_module.sh
  scripts/testing/run_e2e_module_tests.sh
  scripts/testing/run_e2e_module_upgrade_during_deletion_tests.sh
Labels: size/L, lgtm, kind/enhancement, cla: yes
