Repository kyma-project/btp-manager, pull requests merged in 2024-05, with the labels that each got.

#690 Sync with main - use bot token to fetch the repo
  .github/workflows/sync-with-main.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#694 Make go linter timeout configurable
  .github/workflows/run-go-linter.yaml
  Makefile
Labels: size/S, lgtm, kind/enhancement, cla: yes

#696 Added Missing Name Substitution
  scripts/testing/yaml/secret.tmpl.yaml
Labels: kind/bug, size/XS, lgtm, cla: yes

#697 Bump Go to 1.22.3
  go.mod
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#674 Service Manager client
  go.mod
  internal/cluster-object/secret_provider.go
  internal/cluster-object/secret_provider_test.go
  internal/cluster-object/service_instance_provider.go
  internal/cluster-object/service_instance_provider_test.go
  internal/service-manager/client.go
  internal/service-manager/types/common.go
  internal/service-manager/types/service_offering.go
  main.go
Labels: size/L, lgtm, cla: yes

#703 Service Manager client ServiceOfferings test
  internal/service-manager/client.go
  internal/service-manager/client_test.go
  internal/service-manager/testdata/service_offerings.json
Labels: size/L, lgtm, cla: yes

#704 Create single-topic docs
  README.md
  docs/user/02-10-usage.md
  docs/user/02-20-create-secret.md
  docs/user/02-30-deploy-service-in-cluster.md
  docs/user/02-40-create-service-instance-with-custom-secret.md
  docs/user/03-10-examples.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#708 Fix a broken link
  README.md
Labels: kind/bug, area/documentation, size/XS, lgtm, cla: yes
