Repository kyma-project/btp-manager, pull requests merged in 2025-05, with the labels that each got.

#1042 Add real secrets to performance tests
  .github/workflows/run-performance-tests-reusable.yaml
Labels: kind/enhancement

#1045 Make tests stable again
  Makefile
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_certificates_test.go
  controllers/btpoperator_controller_provisioning_test.go
  controllers/serviceinstance_controller.go
  controllers/suite_test.go
  controllers/utils_test.go
  internal/certs/certs.go
  internal/certs/certs_test.go
Labels: kind/bug

#1055 Add the doc on updating a service instance
  README.md
  docs/user/03-10-preconfigured-secret.md
  docs/user/03-31-update-service-instances.md
  docs/user/03-32-delete-bindings-and-instances.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, area/documentation, kind/enhancement
