Repository kyma-project/btp-manager, pull requests merged in 2025-01, with the labels that each got.

#948 Custom secret tests not run by default
  controllers/btpoperator_controller_secret_customization_test.go
  controllers/instance_binding_controller_manager.go
  controllers/suite_test.go
  controllers/utils_test.go
Labels: size/L, kind/enhancement, cla: yes

#950 Test case extended
  controllers/btpoperator_controller_secret_customization_test.go
Labels: size/S, lgtm, kind/enhancement

#956 Add info on WatchParametersFromChanges
  docs/user/03-60-pass-parameters.md
  docs/user/resources/02-20-service-instance-cr.md
Labels: documentation, size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#957 Add E2E Service Instance reconciliation when parameters from Secret change test
  docs/contributor/05-20-e2e_tests.md
  scripts/testing/run_e2e_module_tests.sh
  scripts/testing/yaml/e2e-test-si-param-secret.yaml
Labels: area/documentation, size/M, lgtm, kind/enhancement, cla: yes

#959 Fix E2E module tests - export secret name env
  scripts/testing/run_e2e_module_tests.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#961 Fix SI and SB names in E2E module tests
  scripts/testing/run_e2e_module_tests.sh
Labels: size/XS, lgtm, kind/enhancement, cla: yes
