Repository kyma-project/btp-manager, pull requests merged in 2025-02, with the labels that each got.

#933 Add the doc on Secret customization
  docs/assets/module_credentials.drawio.svg
  docs/assets/module_credentials_customized.drawio.svg
  docs/user/03-10-preconfigured-secret.md
  docs/user/03-11-customize_secret.md
  docs/user/03-30-create-instances-and-bindings.md
  docs/user/03-70-delete-bindings-and-instances.md
  docs/user/README.md
Labels: documentation, size/L, area/documentation, lgtm, kind/enhancement, cla: yes

#976 Bump alpine to 1.23.6
  Dockerfile
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#974 Auto merging bump PR for release workflow
  .github/workflows/create-release.yaml
  scripts/create_sec_scanner_bump_pr.sh
  scripts/merge_pr.sh
Labels: size/L, kind/enhancement, cla: yes

#978 Label fixed in release workflow
  .github/workflows/create-release.yaml
  sec-scanners-config.yaml
Labels: size/XS, kind/enhancement, cla: yes

#981 Sync the user docs with the module documentation on Help Portal
  docs/assets/module_credentials.drawio.svg
  docs/assets/module_credentials_customized.drawio.svg
  docs/user/03-11-customize_secret.md
Labels: documentation, size/S, area/documentation, lgtm, kind/enhancement, cla: yes

#971 BTP Manager secret customization
  config/rbac/role.yaml
  controllers/btpoperator_controller.go
  controllers/btpoperator_controller_secret_customization_test.go
  controllers/btpoperator_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  docs/contributor/02-10-operations.md
  docs/user/resources/02-10-sap-btp-operator-cr.md
  internal/conditions/conditions.go
  main.go
  scripts/testing/run_e2e_sap_btp_manager_secret_test.sh
Labels: kind/feature, area/documentation, size/XXL, lgtm, cla: yes

#984 Fix cluster ID secret removal during module deprovisioning
  controllers/btpoperator_controller.go
Labels: size/S, lgtm, kind/enhancement, cla: yes

#990 Since secret customization is merged customization tests are required
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, kind/enhancement, cla: yes

#993 Migrate to Checkmarx One
  scripts/create_scan_config.sh
  sec-scanners-config.yaml
Labels: size/M, kind/enhancement, cla: yes

#994 Incorrect Quotes
  scripts/create_scan_config.sh
  sec-scanners-config.yaml
Labels: kind/bug, size/XS, lgtm, cla: yes

#997 Add id token write permission to release
  .github/workflows/create-release.yaml
Labels: size/XS, kind/enhancement, cla: yes
